---
ID: "c89102ff-84a0-4def-98f2-34895482fb9a"
Parent: "14e4990c-0ec4-4f7f-ba83-a3fa8acdd941"
Template: "14e4990c-0ec4-4f7f-ba83-a3fa8acdd941"
Path: /sitecore/templates/Foundation/SecurityHeaders/Settings/Content Security Policy/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180319T232401Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
