---
ID: "58f3e266-521f-4d6d-acda-e4f6b8701a16"
Parent: "04aa9242-b0ff-4967-97cc-aa1ad97a7fd5"
Template: "d2923fee-da4e-49be-830c-e27764dfa269"
Path: /sitecore/system/Settings/Foundation/SecurityHeader/Enums/Policies/Default
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 50
- ID: "f917c951-1f75-4d62-b14a-bc6888d7eeca"
  Hint: Value
  Value: "default-src"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180417T182246Z
